spring:
  application:
    name: cinema

  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

cinema:
  time-zone: Asia/Ho_Chi_Minh

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000 # 15 phút

scheduler:
  booking-expiration:
    initial-delay: 10000
    fixed-delay: 30000

vnpay:
  version: 2.1.0
  tmn-code: ${YOUR_TMN_CODE}
  hash-secret: ${YOUR_HASH_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:3000/payment/result
  ipn-url: http://localhost:8080/api/v1/payments/vnpay/ipn
